server {
  listen 80;
  server_name kasperrt.me www.kasperrt.me;
  root /usr/share/nginx/sites/kasperrt.me;
  index index.html;
  location / { try_files $uri $uri/ /index.html; }
  location ~ /\.(?!well-known) { deny all; }
}
