apiVersion: apps/v1
kind: Deployment
metadata:
  name: kasperrt-me
  namespace: kasperrt-me
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kasperrt-me
  template:
    metadata:
      labels:
        app: kasperrt-me
    spec:
      containers:
        - name: kasperrt-me
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi
